language: node_js
node_js:
  - '8'
  - '9'
cache:
  directories:
    - node_modules

script: "npm run-script travis"
after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8480136ea087dfae1908
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
