language: node_js
node_js:
  - 8
  - 10
  - 12
  - node

before_install: 'sudo apt-get update && sudo apt-get install -y graphicsmagick'
cache:
  directories:
    - node_modules

matrix:
  include:
    - name: Lint
      node_js: 12
      script: npm run lint

script: npm run test:ci
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8480136ea087dfae1908
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
