sudo: required
services:
  - docker
language: node_js
node_js:
  - '4'
  - '6'
  - '7'
cache:
  directories:
    - node_modules
addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - libcairo2-dev
      - libjpeg8-dev
      - libgif-dev
      - libpango1.0-dev

env: CXX="g++-4.8" CC="gcc-4.8"

script: "npm run-script travis"
after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8480136ea087dfae1908
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
